#
#  ### Params of the orthopus interface ###
#

#
#  Minimize cartesian velocity coefs : dx
#        
alpha_1:          10.
alpha_2:          10.
alpha_3:          10.
alpha_4:          10.
alpha_5:          10.
alpha_6:          10.
alpha_7:          0.

#
#  Minimize joints velocities coefs : dq
#        
beta_1:           0.1
beta_2:           0.1
beta_3:           0.1
beta_4:           0.1
beta_5:           0.1
beta_6:           0.1

#
#  Minimize cartesian position coefs : x
#        
gamma_1:          5000.
gamma_2:          5000.
gamma_3:          5000.
gamma_4:          5000.
gamma_5:          5000.
gamma_6:          5000.
gamma_7:          0.0


#
#  Saved positions 
#        
home_position:    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
rest_position:   [-1.57079, 0.0, 0.0, -1.57079, -1.57079, +1.57079]

#rest_position:    [0.0, 0.64, -1.397, 0.0, 0.0, 0.0]
##drink_position:   [-1.9523217026638426, -0.3769911184307752, 0.14511166066581424, 1.5512486391725602, 1.1918504396018876, -1.1945033400649192]
#drink_position:   [-1.57079, 0.0, 0.0, 0.0, 0.0, 0.0]
reference_frame             : "ground_link"
move_group_commander_name   : "arm"
allow_replanning            : true
goal_joint_tolerance        : 0.001
goal_position_tolerance     : 0.001
goal_orientation_tolerance  : 0.01
        
planning_plugin             : "ompl_interface/OMPLPlanner"
