#
#  ### Params of the orthopus interface ###
#

#
#  Minimize cartesian velocity coefs : dx
#        
alpha_1:          10.
alpha_2:          10.
alpha_3:          10.
alpha_4:          10.
alpha_5:          10.
alpha_6:          10.
alpha_7:          0.

#
#  Minimize joints velocities coefs : dq
#        
beta_1:           0.1
beta_2:           0.1
beta_3:           0.1
beta_4:           0.1
beta_5:           0.1
beta_6:           0.1

#
#  Minimize cartesian position coefs : x
#        
gamma_1:          0.
gamma_2:          0.
gamma_3:          0.
gamma_4:          0.
gamma_5:          0.
gamma_6:          0.
gamma_7:          0.0


#
#  Saved positions 
#        
home_position:    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
rest_position:    [0.0, 0.64, -1.397, 0.0, 0.0, 0.0]

reference_frame             : "ground_link"
move_group_commander_name   : "arm"
allow_replanning            : true
goal_joint_tolerance        : 0.001
goal_position_tolerance     : 0.001
goal_orientation_tolerance  : 0.01

# Trajectory controller gain (PI)
trajectory_ctrl_p_gain  : 6.0
trajectory_ctrl_i_gain  : 0.1

# Constraint controller gain (PI)
constraint_ctrl_p_gain  : 3.0
constraint_ctrl_i_gain  : 0.1

joint_max_vel  : 0.5
cartesian_max_vel  : 0.8

# Pose goal joints tolerance
pose_goal_joints_tolerance  : 0.025 # rad

goal_orientation_tolerance  : 0.01

